services:
  # GITLAB SERVER
  gitlab:
    image: 'gitlab/gitlab-ce:nightly'
    restart: always
    container_name: gitlab
    hostname: '172.21.121.140'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.21.121.140'
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
    volumes:
      - './gitlab/config:/etc/gitlab'
      - './gitlab/logs:/var/log/gitlab'
      - './gitlab/data:/var/opt/gitlab'
    networks:
      - gitlab-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # RUNNER
  gitlab-runner1:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner1
    hostname: gitlab-runner1
    depends_on:
      - gitlab
    volumes:
     - ./config/gitlab-runner:/etc/gitlab-runner
     - /var/run/docker.sock:/var/run/docker.sock
    networks:
        - gitlab-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  gitlab-network:
    name: gitlab-network